export const ROUTES = {
  root: "/",
  explore: "/explore",
  exhibitions: "/exhibitions",
  exhibitionDetail: (exhibitionId: string) => `/exhibitions/${exhibitionId}`,
  contact: "/contact",
  login: "/login",
  signup: "/signup",
  admin: "/admin",
  adminVisitors: "/admin/visitors",
  adminArtists: "/admin/artists",
  adminArtistProfiles: "/admin/artist-profiles",
  adminCategories: "/admin/categories",
  adminArtworks: "/admin/artworks",
  adminExhibitions: "/admin/exhibitions",
  adminInquiries: "/admin/inquiries",
  adminOrders: "/admin/orders",
  adminReports: "/admin/reports",
  artist: "/artist",
  visitor: "/visitor",
  visitorOrders: "/visitor/orders",
  unauthorized: "/unauthorized",
} as const;
